### ISSUE TITLE
Use colors.blue.500 instead of HEX

### ISSUE THREAD

**Issue by skramstad** [benface/tailwindcss-gradients#10]
Hi.

How do I use theme colors like blue.500 to blue.700 instead of #880412 and #0E1934.

So this works:
`
linearGradients: {
			colors: {
				'blue-darker': ['#182A56', '#0E1934'],
			}
		}
`

but this does not
`linearGradients: {
			colors: theme => ({
				'blue-darker': [theme('colors.blue.500'), theme('colors.green.500')],
			})
		}`

**Comment by hacknug** [comment]
This should work:

```js
linearGradients: theme => ({
	colors: {
		'blue-darker': [ theme('colors.blue.500'), theme('colors.green.500') ],
	},
})
```

**Comment by skramstad** [comment]
I thought I've tested this. Anyways... all good :) Thank you.
Maybe add this to config example to the documentation as well...

**Comment by benface** [comment]
> Maybe add this to config example to the documentation as well...

There is kinda an example under `Usage` > `Advanced`, `repeatingLinearGradients` and `repeatingRadialGradients` use the theme colors directly... but you're right that the docs (the docs of all my plugins really) could be greatly improved. PRs welcome! :)
