### ISSUE TITLE
Set first color code linear gradient

### ISSUE THREAD

**Issue by saifsafwan** [benface/tailwindcss-gradients#14]
Hi, how do you set first color code in linear gradient? By default, the first color code used rgba with same color code as second color code, but the alpha is 0, means transparent.

**Comment by benface** [comment]
Hey @saifsafwan, not sure if you closed this because you found the answer, but if not, you can define multi-color linear gradients with an array:

```
linearGradients: theme => ({
  colors: {
    'purple': [theme('colors.purple.500'), theme('colors.purple.900')],
  },
}),
```

**Comment by saifsafwan** [comment]
Hi, yeah, I already found the answer... Thanks for replying though... Appreciate it!
