### ISSUE TITLE
v3 and tailwind v1.3 causes error

### ISSUE THREAD

**Issue by rowild** [benface/tailwindcss-gradients#19]
I get a strange `require() is not a function` error, when installing v3 alongside tailwindcss v1.3:

```sh
./src/css/main.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: require(...) is not a function
    at Object.<anonymous> (/[path]/tailwind.config.js:310:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at /[path]/node_modules/tailwindcss/lib/index.js:71:107
    at /[path]/node_modules/tailwindcss/lib/processTailwindFeatures.js:32:20
    at LazyResult.run (/[path]/node_modules/postcss/lib/lazy-result.js:295:14)
    at /[path]/node_modules/webpack/lib/NormalModule.js:316:20
    at /[path]/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /[path]/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/[path]/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /[path]/node_modules/postcss-loader/src/index.js:208:9
```

Any idea why this happens? (v2.x works fine).
Thank you!

**Comment by benface** [comment]
Hey @rowild I'm not able to reproduce this. Can you please share your config, or (if you have time) even better, give me access to a simple repo that reproduces the issue?

**Comment by Javid-Izadfar** [comment]
Same here with tailwindcss@1.4.6

**Comment by benface** [comment]
@Javid-Izadfar I still cannot reproduce this, but if you give me access to a codebase where you have this error, I can take a look and hopefully fix.

**Comment by Javid-Izadfar** [comment]
this is my `tailwind.config.js`:
```
module.exports = {
  purge: [],
  theme: {},
  variants: {},
  plugins: [
    require('tailwindcss-gradients')(),
  ],
}
```
with tailwindcss@1.4.6 coupled with vue/cli@4.4.1. I'm on windows 10 running node@10.15.3.
sadly, I can't give you access to codebase right now.

**Comment by benface** [comment]
@Javid-Izadfar Can you please try literally any other Tailwind plugin instead of this one and see if it works?

**Comment by rowild** [comment]
One of my errors seems to have been the plugin inclusion:
```js
plugins: [
  // wrong
  require('tailwindcss-gradients')()
  // right
  require('tailwindcss-gradients')
]
```
(Has this by any chance been the case with a very early tailwindcss version?)

However, "gradients" still do not work, while your "tailwindcss-animations" work fine. I prepare a repo here:
https://github.com/rowild/tailwindcss-plugin-tests

**Comment by rowild** [comment]
BTW: Thank you so much to add the "Black Lives Matter" banner to all of your repos!!! It is great to see involvement here on github, too! 

(Here in Vienna, Austria, there was a demo yesterday. About 50.000 people took part and the police didn't interfere, even though they were supposed to, because people didn't stick to the 1 meter distance rule.)

**Comment by benface** [comment]
Hey @rowild, thank you so much for creating that repo. Unfortunately I cannot reproduce the issue, both plugins work fine here (tried both `npm run dev` and `npm run build`):

<img width="1026" alt="CleanShot 2020-06-07 at 09 56 31@2x" src="https://user-images.githubusercontent.com/1059139/83970734-46da4000-a8a5-11ea-817b-82ab15e424e6.png">

I tried with the latest versions of `node` and `npm` (14.4.0 and 6.14.5 respectively) as well as versions 11.15.0 and 6.7.0 (using `nvm`). No issues at all. :/ I'm running macOS, not sure if that changes anything?

**Comment by rowild** [comment]
Look at that! – I set my whole node environment again (also on Mac, also nvm, with node 11, 12, 14), and look at that again: it works! No idea, what I have messed up! But as long as I know how to get it going again, everything is fine. 
Closing this issue. Thank you for your feedback and help! Stay safe!

**Comment by benface** [comment]
You too!
