### ISSUE TITLE
Hover not working

### ISSUE THREAD

**Issue by amrap030** [benface/tailwindcss-gradients#20]
Hello,

I successfully got gradients on my buttons now but unfortunately hover is not working on those buttons with gradients. Is there any way to get it to work?

**Comment by benface** [comment]
Hi @amrap030! By default the only variant enabled for the gradient utilities is `responsive`, but you can enable the `hover` variant like this:
```js
// tailwind.config.js
{
  variants: {
    linearGradients: ['hover', 'responsive'],
  },
}
```

The `variants` keys that this plugin reads are `backgroundImage` (for the `bg-none` utility), `linearGradients`, `radialGradients`, `conicGradients`, `repeatingLinearGradients`, `repeatingRadialGradients`, and `repeatingConicGradients`.

Let me know if that works for you. If not, please show me your markup and your Tailwind config.
